---
title: "Virtual Workshop on Analysis of Unstructured Text Data"
subtitle: "SSC - Data Science and Analytics Section"

---

## When

Thursday June 4th; 1:00-2:30 and 2:30-4:00

## Github

[All code and data](https://github.com/ssc-datascience/ssc-datascience.github.io)

## Instructors

[Dave Campbell](https://people.math.carleton.ca/~davecampbell/Dave_Campbell.html) and [Nathan Taback](http://utstat.toronto.edu/nathan/)

## R libraries to install
- Data Acquisition tools: gutenbergr, genius, rvest, RSelenium
- Tidyverse Tools: tidyverse, tidytext, dplyr, stringr, janitor, ggplot2
- LDA libraries: topicmodels, tm, lda
- Word2Vec library installs from github:
    - library(devtools)
    - install_github("bmschmidt/wordVectors")
    - library(wordVectors)



# Part 1

## Topics

- R Libraries for Working with Text
- Importing unstructured text into R: copy/paste, external API, webscraping, R libraries
- Regular expressions and text normalization (e.g., tokenization)
- N-Grams
- Word Vectors and Matricies

## Slides and Materials

[Slides - html](workshopslides1.html)

[Slides - pdf](workshopslides1.pdf)

[Slides - Rmd (xaringan)](workshopslides1.Rmd), [css style file](slides.css)

[Justin Trudeau tweets](JT20tweets_may25.csv)

[stringr cheatsheet](https://github.com/rstudio/cheatsheets/blob/master/strings.pdf)

<iframe width="560" height="315" src="https://www.youtube.com/embed/LyoID6jAi08" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


# Part 2 

## Topics

Statistical Models for Unstructured Text 

- Sentiment analysis models
- Topic modelling; LDA and what about inference?
- Word2Vec, what it is and what about inference
- Open problems and general discussion

## Slides and Materials

[LDA - md](LDA.md), [LDA - html](LDA.html)

[Sentiment-Analysis - md](Sentiment-Analysis.md), [Sentiment-Analysis - html](Sentiment-Analysis.html)

[Word2Vec - md](Word2Vec.md), [Word2Vec - html](Word2Vec.html)


<iframe width="560" height="315" src="https://www.youtube.com/embed/1wpUeqXO_h8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
